name: npm build and upload artifact

on:
  workflow_call:
    secrets:
      NEXUS_USERNAME:
        required: true
        description: "Nexus login username."
      NEXUS_PASSWORD:
        required: true
        description: "Nexus login password."

    inputs:
      node-version:
        required: false
        type: string
        description: "What Node.js version to use."
        default: "20"
      package-manager:
        required: false
        type: string
        description: "Package manager to use. Default is pnpm."
        default: "pnpm"
      working-directory:
        required: false
        type: string
        default: "."
      artifact-name:
        required: false
        type: string
        default: "node-artifact"
      artifact-path:
        required: false
        type: string
        default: "" # What to upload as artifact
      git-sha:
        required: false
        type: string
        description: "Git SHA to use for versioning"
        default: ${{ github.event.pull_request.head.sha || github.sha }}

    outputs:
      artifact-name:
        description: The name of the artifact generated by the build
        value: ${{ inputs.artifact-name }}
      artifact-path:
        description: Where the artifact is stored in the working directory.
        value: ${{ inputs.artifact-path }}

jobs:
  build:
    name: node build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Fetch all history for all branches and tags (for branches)
          ref: ${{ inputs.git-sha }}

      - name: Check package manager
        run: |
          if [[ "${{ inputs.package-manager }}" != "npm" && "${{ inputs.package-manager }}" != "pnpm" ]]; then
            echo "Unsupported package manager: ${{ inputs.package-manager }}"
            exit 1
          fi

      - uses: nsbno/platform-actions/.github/actions/tools/npm@autodiscovery
        if: ${{ inputs.package-manager == 'npm' }}
        name: npm Build
        with:
          node-version: ${{ inputs.node-version }}
          npm-operations: build
          working-directory: ${{ inputs.working-directory }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          git-sha: ${{ inputs.git-sha }}

      - uses: nsbno/platform-actions/.github/actions/tools/pnpm@autodiscovery
        if: ${{ inputs.package-manager == 'pnpm' }}
        name: pnpm Build
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-operations: build
          working-directory: ${{ inputs.working-directory }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          git-sha: ${{ inputs.git-sha }}

      - name: Store build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{inputs.working-directory}}/${{ inputs.artifact-path }}
          retention-days: 5
